/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NhBug } from '../../models/nh-bug';

export interface NhBugsGet$Params {

/**
 * Your UUID secret key, granted to you by the Nookipedia team. Required for accessing the API.
 */
  'X-API-KEY': string;

/**
 * The version of the API you are calling, written as `1.0.0`. This is specified as required as good practice, but it is not actually enforced by the API. If you do not specify a version, you will be served the latest version, which may eventually result in breaking changes.
 */
  'Accept-Version': string;

/**
 * Retrieve only the bug that are available in a specific month. Value may be the month's name (`jan`, `january`), the integer representing the month (`01`, `1`), or `current` for the current month. When `current` is specified, the return body will be an object with two arrays inside, one called `north` and the other `south` containing the bug available in each respective hemisphere. Note that the current month is calculated based off the API server's time, so it may be slightly off for you at the beginning or end of the month.
 */
  month?: string;

/**
 * When set to `true`, only bug names are returned. Instead of an array of objects with all details, the return will be an array of strings. This is particularly useful when used with the `month` filter, for users who want just a list of bugs in a given month but not all their respective details.
 */
  excludedetails?: string;

/**
 * Specify the desired width of returned image URLs. When unspecified, the linked image(s) returned by the API will be full-resolution. Note that images can only be reduced in size; specifying a width greater than than the maximum size will return the default full-size image URL. Note that requesting specific image sizes for long lists may result in a very long response time.
 */
  thumbsize?: number;
}

export function nhBugsGet(http: HttpClient, rootUrl: string, params: NhBugsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NhBug>>> {
  const rb = new RequestBuilder(rootUrl, nhBugsGet.PATH, 'get');
  if (params) {
    rb.header('X-API-KEY', params['X-API-KEY'], {});
    rb.header('Accept-Version', params['Accept-Version'], {});
    rb.query('month', params.month, {});
    rb.query('excludedetails', params.excludedetails, {});
    rb.query('thumbsize', params.thumbsize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<NhBug>>;
    })
  );
}

nhBugsGet.PATH = '/nh/bugs';
