/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NhClothing } from '../../models/nh-clothing';

export interface NhClothingGet$Params {

/**
 * Your UUID secret key, granted to you by the Nookipedia team. Required for accessing the API.
 */
  'X-API-KEY': string;

/**
 * The version of the API you are calling, written as `1.0.0`. This is specified as required as good practice, but it is not actually enforced by the API. If you do not specify a version, you will be served the latest version, which may eventually result in breaking changes.
 */
  'Accept-Version': string;

/**
 * Specify the category of clothing to return.
 */
  category?: 'Tops' | 'Bottoms' | 'Dress-up' | 'Headwear' | 'Accessories' | 'Socks' | 'Shoes' | 'Bags' | 'Umbrellas';

/**
 * Return clothing that matches the provided colors (may specify one or two colors). Colors are used for gifting villagers.
 */
  color?: Array<'Aqua' | 'Beige' | 'Black' | 'Blue' | 'Brown' | 'Colorful' | 'Gray' | 'Green' | 'Orange' | 'Pink' | 'Purple' | 'Red' | 'White' | 'Yellow'>;

/**
 * Return clothing that matches the provided styles (may specify one or two styles). Styles are used for gifting villagers.
 */
  style?: Array<'Active' | 'Cool' | 'Cute' | 'Elegant' | 'Gorgeous' | 'Simple'>;

/**
 * Return clothing that have the specified Label theme. This is used for completing the requested outfit theme for [Label](https://nookipedia.com/wiki/Label) when she visits the player's island.
 */
  labeltheme?: 'Comfy' | 'Everyday' | 'Fairy tale' | 'Formal' | 'Goth' | 'Outdoorsy' | 'Party' | 'Sporty' | 'Theatrical' | 'Vacation' | 'Work';

/**
 * When set to `true`, only clothing names are returned. Instead of an array of objects with all details, the return will be an array of strings.
 */
  excludedetails?: string;
}

export function nhClothingGet(http: HttpClient, rootUrl: string, params: NhClothingGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NhClothing>>> {
  const rb = new RequestBuilder(rootUrl, nhClothingGet.PATH, 'get');
  if (params) {
    rb.header('X-API-KEY', params['X-API-KEY'], {});
    rb.header('Accept-Version', params['Accept-Version'], {});
    rb.query('category', params.category, {});
    rb.query('color', params.color, {});
    rb.query('style', params.style, {});
    rb.query('labeltheme', params.labeltheme, {});
    rb.query('excludedetails', params.excludedetails, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<NhClothing>>;
    })
  );
}

nhClothingGet.PATH = '/nh/clothing';
