/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NhEvent } from '../../models/nh-event';

export interface NhEventsGet$Params {

/**
 * Your UUID secret key, granted to you by the Nookipedia team. Required for accessing the API.
 */
  'X-API-KEY': string;

/**
 * The version of the API you are calling, written as `1.0.0`. This is specified as required as good practice, but it is not actually enforced by the API. If you do not specify a version, you will be served the latest version, which may eventually result in breaking changes.
 */
  'Accept-Version': string;

/**
 * Specify a specific date (in the current or next year) to retrieve events for. Accepts many date formats, such as `YYYY-MM-DD` or `Month Day, Year`, as well as `today` to retrieve the current day's events (UTC time).
 */
  date?: string;

/**
 * Specify the year to retrieve events for. Must be the current or next year.
 */
  year?: string;

/**
 * Specify the month to retrieve events for (accepts multiple formats, such as `Oct`, `October`, or `10`). Most likely want to use alongside `year`, otherwise events in both the current and next year are returned.
 */
  month?: string;

/**
 * Specify the day of the month to retrieve events for.
 */
  day?: number;
}

export function nhEventsGet(http: HttpClient, rootUrl: string, params: NhEventsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NhEvent>>> {
  const rb = new RequestBuilder(rootUrl, nhEventsGet.PATH, 'get');
  if (params) {
    rb.header('X-API-KEY', params['X-API-KEY'], {});
    rb.header('Accept-Version', params['Accept-Version'], {});
    rb.query('date', params.date, {});
    rb.query('year', params.year, {});
    rb.query('month', params.month, {});
    rb.query('day', params.day, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<NhEvent>>;
    })
  );
}

nhEventsGet.PATH = '/nh/events';
