/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NhFurniture } from '../../models/nh-furniture';

export interface NhFurnitureGet$Params {

/**
 * Your UUID secret key, granted to you by the Nookipedia team. Required for accessing the API.
 */
  'X-API-KEY': string;

/**
 * The version of the API you are calling, written as `1.0.0`. This is specified as required as good practice, but it is not actually enforced by the API. If you do not specify a version, you will be served the latest version, which may eventually result in breaking changes.
 */
  'Accept-Version': string;

/**
 * Specify the category of furniture to return (housewares, miscellaneous, wall-mounted, or ceiling decor).
 */
  category?: 'Housewares' | 'Miscellaneous' | 'Wall-mounted' | 'Ceiling decor';

/**
 * Return furniture that matches the provided colors (may specify one or two colors).
 */
  color?: Array<'Aqua' | 'Beige' | 'Black' | 'Blue' | 'Brown' | 'Colorful' | 'Gray' | 'Green' | 'Orange' | 'Pink' | 'Purple' | 'Red' | 'White' | 'Yellow'>;

/**
 * When set to `true`, only furniture names are returned. Instead of an array of objects with all details, the return will be an array of strings.
 */
  excludedetails?: string;
}

export function nhFurnitureGet(http: HttpClient, rootUrl: string, params: NhFurnitureGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NhFurniture>>> {
  const rb = new RequestBuilder(rootUrl, nhFurnitureGet.PATH, 'get');
  if (params) {
    rb.header('X-API-KEY', params['X-API-KEY'], {});
    rb.header('Accept-Version', params['Accept-Version'], {});
    rb.query('category', params.category, {});
    rb.query('color', params.color, {});
    rb.query('excludedetails', params.excludedetails, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<NhFurniture>>;
    })
  );
}

nhFurnitureGet.PATH = '/nh/furniture';
