/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NhRecipe } from '../../models/nh-recipe';

export interface NhRecipesGet$Params {

/**
 * Your UUID secret key, granted to you by the Nookipedia team. Required for accessing the API.
 */
  'X-API-KEY': string;

/**
 * The version of the API you are calling, written as `1.0.0`. This is specified as required as good practice, but it is not actually enforced by the API. If you do not specify a version, you will be served the latest version, which may eventually result in breaking changes.
 */
  'Accept-Version': string;

/**
 * Specify a material to only get recipes that use that material. You can specify `material` up to six times (no recipe uses more than six materials).
 */
  material?: string;

/**
 * When set to `true`, only recipe names are returned. Instead of an array of objects with all details, the return will be an array of strings.
 */
  excludedetails?: string;

/**
 * Specify the desired width of returned image URLs. When unspecified, the linked image(s) returned by the API will be full-resolution. Note that images can only be reduced in size; specifying a width greater than than the maximum size will return the default full-size image URL. Note that requesting specific image sizes for long lists may result in a very long response time.
 */
  thumbsize?: number;
}

export function nhRecipesGet(http: HttpClient, rootUrl: string, params: NhRecipesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NhRecipe>>> {
  const rb = new RequestBuilder(rootUrl, nhRecipesGet.PATH, 'get');
  if (params) {
    rb.header('X-API-KEY', params['X-API-KEY'], {});
    rb.header('Accept-Version', params['Accept-Version'], {});
    rb.query('material', params.material, {});
    rb.query('excludedetails', params.excludedetails, {});
    rb.query('thumbsize', params.thumbsize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<NhRecipe>>;
    })
  );
}

nhRecipesGet.PATH = '/nh/recipes';
