/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NhSeaCreature } from '../../models/nh-sea-creature';

export interface NhSeaSeaCreatureGet$Params {

/**
 * The name of the sea creature you wish to retrieve information about.
 */
  sea_creature: string;

/**
 * Your UUID secret key, granted to you by the Nookipedia team. Required for accessing the API.
 */
  'X-API-KEY': string;

/**
 * The version of the API you are calling, written as `1.0.0`. This is specified as required as good practice, but it is not actually enforced by the API. If you do not specify a version, you will be served the latest version, which may eventually result in breaking changes.
 */
  'Accept-Version': string;

/**
 * Specify the desired width of returned image URLs. When unspecified, the linked image(s) returned by the API will be full-resolution. Note that images can only be reduced in size; specifying a width greater than than the maximum size will return the default full-size image URL.
 */
  thumbsize?: number;
}

export function nhSeaSeaCreatureGet(http: HttpClient, rootUrl: string, params: NhSeaSeaCreatureGet$Params, context?: HttpContext): Observable<StrictHttpResponse<NhSeaCreature>> {
  const rb = new RequestBuilder(rootUrl, nhSeaSeaCreatureGet.PATH, 'get');
  if (params) {
    rb.path('sea_creature', params.sea_creature, {});
    rb.header('X-API-KEY', params['X-API-KEY'], {});
    rb.header('Accept-Version', params['Accept-Version'], {});
    rb.query('thumbsize', params.thumbsize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NhSeaCreature>;
    })
  );
}

nhSeaSeaCreatureGet.PATH = '/nh/sea/{sea_creature}';
