/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Villager } from '../../models/villager';

export interface VillagersGet$Params {

/**
 * Your UUID secret key, granted to you by the Nookipedia team. Required for accessing the API.
 */
  'X-API-KEY': string;

/**
 * The version of the API you are calling, written as `1.0.0`. This is specified as required as good practice, but it is not actually enforced by the API. If you do not specify a version, you will be served the latest version, which may eventually result in breaking changes.
 */
  'Accept-Version': string;

/**
 * Villager name. For most names you will get back an array with one object, but note that names are not a unique identifier across the series, as there are 3 names that are shared by multiple villagers (Lulu, Petunia, Carmen). For those 3 names you will get back an array with 2 objects. How you disambiguate between these villagers is up to you.
 */
  name?: string;

/**
 * Retrieve villagers of a certain species.
 */
  species?: 'alligator' | 'anteater' | 'bear' | 'bear cub' | 'bird' | 'bull' | 'cat' | 'cub' | 'chicken' | 'cow' | 'deer' | 'dog' | 'duck' | 'eagle' | 'elephant' | 'frog' | 'goat' | 'gorilla' | 'hamster' | 'hippo' | 'horse' | 'koala' | 'kangaroo' | 'lion' | 'monkey' | 'mouse' | 'octopus' | 'ostrich' | 'penguin' | 'pig' | 'rabbit' | 'rhino' | 'rhinoceros' | 'sheep' | 'squirrel' | 'tiger' | 'wolf';

/**
 * Retrieve villagers with a certain personality. For 'sisterly', note that the community often also calls it 'uchi' or 'big sister'.
 */
  personality?: 'big sister' | 'cranky' | 'jock' | 'lazy' | 'normal' | 'peppy' | 'sisterly' | 'smug' | 'snooty';

/**
 * Retrieve villagers that appear in all listed games. For example, if you want only villagers that appear in both *New Horizons* and *Pocket Camp*, you would send in `?game=nh&game=pc`.
 */
  game?: Array<'DNM' | 'AC' | 'E_PLUS' | 'WW' | 'CF' | 'NL' | 'WA' | 'NH' | 'FILM' | 'HHD' | 'PC'>;

/**
 * Retrieve villagers born in a specific month. Value may be the month's name (`jan`, `january`) or the integer representing the month (`01`, `1`).
 */
  birthmonth?: string;

/**
 * Use with `birthmonth` to get villager(s) born on a specific day. Value should be an int, 1 through 31.
 */
  birthday?: string;

/**
 * When set to `true`, an `nh_details` object will be included that contains *New Horizons* details about the villager. If the villager does not appear in *New Horizons*, the returned `nh_details` field will be set to null.
 */
  nhdetails?: string;

/**
 * When set to `true`, only villager names are returned. Instead of an array of objects with all details, the return will be an array of strings.
 */
  excludedetails?: string;

/**
 * Specify the desired width of returned image URLs. When unspecified, the linked image(s) returned by the API will be full-resolution. Note that images can only be reduced in size; specifying a width greater than than the maximum size will return the default full-size image URL. Note that requesting specific image sizes for long lists may result in a very long response time.
 */
  thumbsize?: number;
}

export function villagersGet(http: HttpClient, rootUrl: string, params: VillagersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Villager>>> {
  const rb = new RequestBuilder(rootUrl, villagersGet.PATH, 'get');
  if (params) {
    rb.header('X-API-KEY', params['X-API-KEY'], {});
    rb.header('Accept-Version', params['Accept-Version'], {});
    rb.query('name', params.name, {});
    rb.query('species', params.species, {});
    rb.query('personality', params.personality, {});
    rb.query('game', params.game, {});
    rb.query('birthmonth', params.birthmonth, {});
    rb.query('birthday', params.birthday, {});
    rb.query('nhdetails', params.nhdetails, {});
    rb.query('excludedetails', params.excludedetails, {});
    rb.query('thumbsize', params.thumbsize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Villager>>;
    })
  );
}

villagersGet.PATH = '/villagers';
