/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Error400 } from './models/error-400';
export type { Error401 } from './models/error-401';
export type { Error404 } from './models/error-404';
export type { Error500 } from './models/error-500';
export type { NhArtwork } from './models/nh-artwork';
export type { NhBug } from './models/nh-bug';
export type { NhClothing } from './models/nh-clothing';
export type { NhEvent } from './models/nh-event';
export type { NhFish } from './models/nh-fish';
export type { NhFossilGroup } from './models/nh-fossil-group';
export type { NhFossilGroupWithIndividualFossils } from './models/nh-fossil-group-with-individual-fossils';
export type { NhFossilGroupWithIndividualFossilsNoMatched } from './models/nh-fossil-group-with-individual-fossils-no-matched';
export type { NhFurniture } from './models/nh-furniture';
export type { NhGyroid } from './models/nh-gyroid';
export type { NhIndividualFossil } from './models/nh-individual-fossil';
export type { NhInterior } from './models/nh-interior';
export type { NhItem } from './models/nh-item';
export type { NhPhoto } from './models/nh-photo';
export type { NhRecipe } from './models/nh-recipe';
export type { NhSeaCreature } from './models/nh-sea-creature';
export type { NhTool } from './models/nh-tool';
export type { Villager } from './models/villager';
