/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Bad request (often an invalid input).
 */
export interface Error400 {

  /**
   * A more in-depth description of the issue, including parameters and/or error text when available.
   */
  details?: string;

  /**
   * A brief title describing the error.
   */
  title?: string;
}
