/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Internal server error.
 */
export interface Error500 {

  /**
   * A more in-depth description of the issue, including parameters and/or error text when available.
   */
  details?: string;

  /**
   * A brief title describing the error.
   */
  title?: string;
}
