/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NhArtwork {

  /**
   * The name of the real-life analog to the artwork.
   */
  art_name?: string;

  /**
   * The art style of the artwork.
   */
  art_style?: string;

  /**
   * The type of artwork (either a painting or statue).
   */
  art_type?: 'Painting' | 'Statue';

  /**
   * The author of the real-life analog to the artwork.
   */
  author?: string;

  /**
   * The availability of the artwork.
   */
  availability?: string;

  /**
   * The number of Bells the artwork may be purchased for.
   */
  buy?: number;

  /**
   * Information about the fake version of the artwork. If there is no fake, `fake_info`'s value will be `null`.
   */
  fake_info?: {

/**
 * Image of the fake artwork.
 */
'image_url'?: string;

/**
 * The texture of the artwork. Note that statues will not have a texture (value will be empty string).
 */
'texture_url'?: string;

/**
 * A description of how to identify the fake artwork.
 */
'description'?: string;
};

  /**
   * Whether the artwork has a fake or not.
   */
  has_fake?: boolean;

  /**
   * The length of the artwork.
   */
  length?: number;

  /**
   * Name of the artwork.
   */
  name?: string;

  /**
   * Information about the genuine version of the artwork.
   */
  real_info?: {

/**
 * Image of the real artwork.
 */
'image_url'?: string;

/**
 * The texture of the artwork. Note that statues will not have a texture (value will be empty string).
 */
'texture_url'?: string;

/**
 * The description of the artwork.
 */
'description'?: string;
};

  /**
   * The number of Bells the artwork can be sold to Nook's store for, when it is genuine.
   */
  sell?: number;

  /**
   * Link to the respective Nookipedia article.
   */
  url?: string;

  /**
   * The width of the artwork.
   */
  width?: number;

  /**
   * The year that the real-life analog was made. May be an exact year, an estimate ("circa"), or a range.
   */
  year?: string;
}
