/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NhClothing {

  /**
   * Where the clothing may be obtained from (could be multiple sources). `from` is a brief description of the source; `note`, when provided, provides additional details.
   */
  availability?: Array<{
'from'?: string;
'note'?: string;
}>;

  /**
   * An array of prices, for when the item may be purchased with Bells, Nook Miles, etc..
   */
  buy?: Array<{
'price'?: number;
'currency'?: string;
}>;

  /**
   * The category of item as shown in the player's inventory.
   */
  category?: 'Tops' | 'Bottoms' | 'Dress-up' | 'Headwear' | 'Accessories' | 'Socks' | 'Shoes' | 'Bags' | 'Umbrellas';

  /**
   * The clothing's Label theme(s). This is used for completing the requested outfit theme for [Label](https://nookipedia.com/wiki/Label) when she visits the player's island.
   */
  label_themes?: Array<'Comfy' | 'Everyday' | 'Fairy tale' | 'Formal' | 'Goth' | 'Outdoorsy' | 'Party' | 'Sporty' | 'Theatrical' | 'Vacation' | 'Work'>;

  /**
   * The name of the clothing.
   */
  name?: string;

  /**
   * Any additional miscellaneous information about the clothing, such as a name change from a past update.
   */
  notes?: string;

  /**
   * The time of the year that the clothing is available.
   */
  seasonality?: string;

  /**
   * The number of Bells the clothing can be sold to the store for.
   */
  sell?: number;

  /**
   * The clothing's style(s). Styles are used for gifting villagers.
   */
  styles?: Array<'Active' | 'Cool' | 'Cute' | 'Elegant' | 'Gorgeous' | 'Simple'>;

  /**
   * Whether the item is available through legitimate gameplay. Some items are added to the game files in an update, but aren't actually made available until a subsequent update unlocks them.
   */
  unlocked?: boolean;

  /**
   * Link to the respective Nookipedia article.
   */
  url?: string;

  /**
   * The total number of variations the clothing has, between 0 and 8.
   */
  variation_total?: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

  /**
   * An array of objects, each object representing a variation of the clothing. Clothing that has no variations (only one version) will have a single variation object with the image URL and colors, but the `variation` field will be empty. Clothing with multiple variations will have the `variation` fields defined with the name of each variation.
   */
  variations?: Array<{
'variation'?: string;
'image_url'?: string;
'colors'?: Array<'Aqua' | 'Beige' | 'Black' | 'Blue' | 'Brown' | 'Colorful' | 'Gray' | 'Green' | 'Orange' | 'Pink' | 'Purple' | 'Red' | 'White' | 'Yellow'>;
}>;

  /**
   * The version of *New Horizons* that the item was added. Items that were included at the game's launch have version "1.0.0".
   */
  version_added?: string;

  /**
   * Whether villagers may equip this item.
   */
  vill_equip?: boolean;
}
