/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NhFossilGroupWithIndividualFossilsNoMatched {

  /**
   * A description of the fossil group.
   */
  description?: string;

  /**
   * An array of objects, each object representing a fossil that belongs to the given group.
   */
  fossils?: Array<{
'name'?: string;
'url'?: string;
'image_url'?: string;
'fossil_group'?: string;
'interactable'?: boolean;
'sell'?: number;
'hha_base'?: number;
'width'?: number;
'length'?: number;
'colors'?: Array<'Aqua' | 'Beige' | 'Black' | 'Blue' | 'Brown' | 'Colorful' | 'Gray' | 'Green' | 'Orange' | 'Pink' | 'Purple' | 'Red' | 'White' | 'Yellow'>;
}>;

  /**
   * The name of the fossil group.
   */
  name?: string;

  /**
   * The room where the fossil group can be found in the museum's fossil section.
   */
  room?: number;

  /**
   * Link to the respective Nookipedia article.
   */
  url?: string;
}
