/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NhFossilGroup {

  /**
   * A description of the fossil group.
   */
  description?: string;

  /**
   * The name of the fossil group.
   */
  name?: string;

  /**
   * The room where the fossil group can be found in the museum's fossil section.
   */
  room?: number;

  /**
   * Link to the respective Nookipedia article.
   */
  url?: string;
}
