/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NhGyroid {

  /**
   * Where the gyroid may be obtained from (could be multiple sources). `from` is a brief description of the source; `note`, when provided, provides additional details.
   */
  availability?: Array<{
'from'?: string;
'note'?: string;
}>;

  /**
   * An array of prices, for when the item may be purchased with Bells, Nook Miles, etc..
   */
  buy?: Array<{
'price'?: number;
'currency'?: string;
}>;

  /**
   * If the item has variations, this is the name of the furniture part that changes. For example, for many bamboo items, the custom body part is "Bamboo" as the bamboo color is able to be customized.
   */
  custom_body_part?: string;

  /**
   * The item that needs to be consumed to customize this item. The vast majority are "Customization Kit", but a small selection of items will require a different item, such as items in the Spooky Series requiring pumpkins.
   */
  custom_kit_type?: string;

  /**
   * The number of `custom_kit_type`s (e.g. Customization Kits) that are needed to customize this item. Value is 0 if the item is not customizable.
   */
  custom_kits?: number;

  /**
   * Whether or not the item is customizable via a crafting table.
   */
  customizable?: boolean;

  /**
   * How much Cyrus will charge to customize this gyroid. Currently it's a flat rate of 1,000 bells for every gyroid.
   */
  cyrus_price?: number;

  /**
   * The number of lengthwise grid spaces this item takes up.
   */
  grid_length?: number;

  /**
   * The number of widthwise grid spaces this item takes up.
   */
  grid_width?: number;

  /**
   * The base value that the item provides to a player's Happy Home Academy score when placed in their home.
   */
  hha_base?: number;

  /**
   * The name of the gyroid.
   */
  name?: string;

  /**
   * Any additional miscellaneous information about the gyroid, such as a name change from a past update.
   */
  notes?: string;

  /**
   * The number of Bells the gyroid can be sold to the store for.
   */
  sell?: number;

  /**
   * The type of sound this gyroid makes.
   */
  sound?: 'Crash' | 'Drum set' | 'Hi-hat' | 'Kick' | 'Melody' | 'Snare';

  /**
   * Whether the item is available through legitimate gameplay. Some items are added to the game files in an update, but aren't actually made available until a subsequent update unlocks them.
   */
  unlocked?: boolean;

  /**
   * Link to the respective Nookipedia article.
   */
  url?: string;

  /**
   * The total number of variations the gyroid has, between 0 and 7.
   */
  variation_total?: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;

  /**
   * An array of objects, each object representing a variation of the gyroid. Gyroids that has no variations (only one version) will have a single variation object with the image URL and colors, but the `variation` field will be empty. Gyroids with multiple variations will have the `variation` fields defined with the name of each variation.
   */
  variations?: Array<{
'variation'?: string;
'image_url'?: string;
'colors'?: Array<'Aqua' | 'Beige' | 'Black' | 'Blue' | 'Brown' | 'Colorful' | 'Gray' | 'Green' | 'Orange' | 'Pink' | 'Purple' | 'Red' | 'White' | 'Yellow'>;
}>;

  /**
   * The version of *New Horizons* that the item was added. Items that were included at the game's launch have version "1.0.0".
   */
  version_added?: string;
}
