/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NhItem {

  /**
   * Where the clothing may be obtained from (could be multiple sources). `from` is a brief description of the source; `note`, when provided, provides additional details.
   */
  availability?: Array<{
'from'?: string;
'note'?: string;
}>;

  /**
   * An array of prices, for when the interior may be purchased with Bells, Nook Miles, etc..
   */
  buy?: Array<{
'price'?: number;
'currency'?: string;
}>;

  /**
   * Whether the item is edible or not.
   */
  edible?: boolean;

  /**
   * The base value that the item provides to a player's Happy Home Academy score when placed in their home.
   */
  hha_base?: number;

  /**
   * Image of the interior.
   */
  image_url?: string;

  /**
   * Whether or not the item is a fence or not.
   */
  is_fence?: boolean;

  /**
   * (WIP)
   */
  material_name_sort?: number;

  /**
   * (WIP)
   */
  material_seasonality?: string;

  /**
   * (WIP)
   */
  material_seasonality_sort?: number;

  /**
   * (WIP)
   */
  material_sort?: number;

  /**
   * (WIP)
   */
  material_type?: '' | 'Bamboo' | 'Mushroom' | 'Trash' | 'Wood' | 'Ore' | 'Snowflake' | 'Tree' | 'Ornament' | 'Fruit' | 'Underwater' | 'Other' | 'Leaf' | 'Shell' | 'Flower' | 'Star Fragment' | 'Feather' | 'Egg' | 'Plant';

  /**
   * The name of the item.
   */
  name?: string;

  /**
   * Any additional miscellaneous information about the item, such as a name change from a past update.
   */
  notes?: string;

  /**
   * (WIP)
   */
  plant_type?: '' | 'Pumpkin' | 'Flower' | 'Bush' | 'Tree';

  /**
   * The number of bells the item can be sold to Nook's store for.
   */
  sell?: number;

  /**
   * How much the item can stack up to in a single inventory slot.
   */
  stack?: number;

  /**
   * Whether the item is available through legitimate gameplay. Some items are added to the game files in an update, but aren't actually made available until a subsequent update unlocks them.
   */
  unlocked?: boolean;

  /**
   * Link to the respective Nookipedia article.
   */
  url?: string;

  /**
   * The version of *New Horizons* that the item was added. Items that were included at the game's launch have version "1.0.0".
   */
  version_added?: string;
}
