/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NhIndividualFossil {
  colors?: Array<'Aqua' | 'Beige' | 'Black' | 'Blue' | 'Brown' | 'Colorful' | 'Gray' | 'Green' | 'Orange' | 'Pink' | 'Purple' | 'Red' | 'White' | 'Yellow'>;

  /**
   * The name of the group that the fossil belongs to.
   */
  fossil_group?: string;

  /**
   * The base value that the item provides to a player's Happy Home Academy score when placed in their home.
   */
  hha_base?: number;

  /**
   * Image of the fossil's icon.
   */
  image_url?: string;

  /**
   * Whether or not the item can be interacted with.
   */
  interactable?: boolean;

  /**
   * The length of the fossil.
   */
  length?: number;

  /**
   * The name of the fossil.
   */
  name?: string;

  /**
   * The number of bells the item can be sold to Nook's store for.
   */
  sell?: number;

  /**
   * Link to the respective Nookipedia article.
   */
  url?: string;

  /**
   * The width of the fossil.
   */
  width?: number;
}
