/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NhRecipe {

  /**
   * Where the recipe may be obtained from. `from` is a brief description of the source; `note`, when provided, provides additional details.
   */
  availability?: Array<{
'from'?: string;
'note'?: string;
}>;

  /**
   * An array of prices, for when the recipe may be purchased with Bells, Nook Miles, etc. The majority of recipes cannot be bought (in which case this array will be empty).
   */
  buy?: Array<{
'price'?: number;
'currency'?: string;
}>;

  /**
   * Image of the item the recipe crafts.
   */
  image_url?: string;

  /**
   * The list of materials required to craft the item.
   */
  materials?: Array<{
'name'?: string;
'count'?: number;
}>;

  /**
   * The name of the recipe.
   */
  name?: string;

  /**
   * How many recipes the player has to have learned to unlock this one.
   */
  recipes_to_unlock?: number;

  /**
   * The number of Bells the sea creature can be sold to Nook's store for.
   */
  sell?: number;

  /**
   * The unique in-game ID of the recipe.
   */
  serial_id?: number;

  /**
   * Link to the respective Nookipedia article.
   */
  url?: string;
}
