/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NhSeaCreature {

  /**
   * An array of possible catchphrases the player says after catching the sea creature. Most critters have just one, but some can have multiple.
   */
  catchphrases?: Array<string>;

  /**
   * Image of the sea creature.
   */
  image_url?: string;

  /**
   * Name of the sea creature.
   */
  name?: string;

  /**
   * When you can catch the sea creature in the Northern hemisphere.
   */
  north?: {

/**
 * An array of objects, each object holding a months string and the time the critter is availabile during the specified month(s) in the northern hemisphere. Most critters will have just one object. A small number of critters have variable time availability in which case this array will have multiple objects.
 */
'availability_array'?: Array<{
'months'?: string;
'time'?: string;
}>;

/**
 * An object with twelve numerical keys, each representing a month (`"1"` for January, `"2"` for February, etc.). The value is the times the critter is available during that month. If the critter is unavailable in a month, the value will be `"NA"`.
 */
'times_by_month'?: {
'1'?: string;
'2'?: string;
'3'?: string;
'4'?: string;
'5'?: string;
'6'?: string;
'7'?: string;
'8'?: string;
'9'?: string;
'10'?: string;
'11'?: string;
'12'?: string;
};

/**
 * The months the sea creature is available for in the Northern hemisphere. If all year, value will be `"All year"`.
 */
'months'?: string;

/**
 * An array of integers representing the months the sea creature is available in the Northern hemisphere.
 */
'months_array'?: Array<number>;
};

  /**
   * In-game sea creature number, marking position in the Critterpedia.
   */
  number?: number;

  /**
   * How rare the sea creature is. Note that this field is currently empty for most sea creatures as we do not yet know how exactly sea creature rarities are calculated in the game code.
   */
  rarity?: string;

  /**
   * Render of the sea creature.
   */
  render_url?: string;

  /**
   * The number of Bells the sea creature can be sold to Nook's store for.
   */
  sell_nook?: number;

  /**
   * Short descriptor of where the sea creature can be found.
   */
  shadow_movement?: 'Stationary' | 'Very slow' | 'Slow' | 'Medium' | 'Fast' | 'Very fast';

  /**
   * Short descriptor of where the sea creature can be found.
   */
  shadow_size?: 'X-Small' | 'Small' | 'Medium' | 'Large' | 'X-Large';

  /**
   * When you can catch the sea creature in the Southern hemisphere.
   */
  south?: {

/**
 * An array of objects, each object holding a months string and the time the critter is availabile during the specified month(s) in the southern hemisphere. Most critters will have just one object. A small number of critters have variable time availability in which case this array will have multiple objects.
 */
'availability_array'?: Array<{
'months'?: string;
'time'?: string;
}>;

/**
 * An object with twelve numerical keys, each representing a month (`"1"` for January, `"2"` for February, etc.). The value is the times the critter is available during that month. If the critter is unavailable in a month, the value will be `"NA"`.
 */
'times_by_month'?: {
'1'?: string;
'2'?: string;
'3'?: string;
'4'?: string;
'5'?: string;
'6'?: string;
'7'?: string;
'8'?: string;
'9'?: string;
'10'?: string;
'11'?: string;
'12'?: string;
};

/**
 * The months the sea creature is available for in the Southern hemisphere. If all year, value will be `"All year"`.
 */
'months'?: string;

/**
 * An array of integers representing the months the sea creature is available in the Southern hemisphere.
 */
'months_array'?: Array<number>;
};

  /**
   * The length of the tank when the sea creature is placed as a furniture item.
   */
  tank_length?: number;

  /**
   * The width of the tank when the sea creature is placed as a furniture item.
   */
  tank_width?: number;

  /**
   * The total number of sea creatures the player has to have caught before this sea creature will start spawning.
   */
  total_catch?: number;

  /**
   * Link to the respective Nookipedia article.
   */
  url?: string;
}
