/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Villager {

  /**
   * A previous name for the villager. A very small number of villagers changed names between earlier games, such as Sally being known as Hazel in the original game.
   */
  alt_name?: string;

  /**
   * List of official media the villager appeared in. `DNM` is *Doubutsu no Mori* for the Nintendo 64 (Japan-exclusive); `AC` is *Animal Crossing* for GameCube; `E_PLUS` is *Doubutsu no Mori e+* for GameCube (expanded port of AC, Japan-exclusive); `WW` is *Wild World* for the DS; `CF` is *City Folk* for Wii; `NL` is *New Leaf* for 3DS; `WA` is *Welcome amiibo*, the *New Leaf* expansion; `NH` is *New Horizons* for Switch; `FILM` is the *Doubutsu no Mori* Japan-exclusive film; `HHD` is *Happy Home Designer* for the Wii; and `PC` is *Pocket Camp* for mobile.
   */
  appearances?: Array<'DNM' | 'AC' | 'E_PLUS' | 'WW' | 'CF' | 'NL' | 'WA' | 'NH' | 'FILM' | 'HHD' | 'PC'>;

  /**
   * Birthday day of the villager. Note that villager birthdays were not introduced until *Wild World*. For villagers who didn't appear in *Wild World* or any later games, this field will be an empty string.
   */
  birthday_day?: string;

  /**
   * Birthday month of the villager. Note that villager birthdays were not introduced until *Wild World*. For villagers who didn't appear in *Wild World* or any later games, this field will be an empty string.
   */
  birthday_month?: string;

  /**
   * The villager's default clothing. This will be the clothing from the latest game (i.e. if the villager had varying phrases between *Wild World* and *New Horizons*, this will be the *New Horizons* clothing).
   */
  clothing?: string;

  /**
   * The first *Animal Crossing* game the villager appeared in. `DNM` is *Doubutsu no Mori* for the Nintendo 64 (Japan-exclusive); `AC` is *Animal Crossing* for GameCube; `E_PLUS` is *Doubutsu no Mori e+* for GameCube (expanded port of AC, Japan-exclusive); `WW` is *Wild World* for the DS; `CF` is *City Folk* for Wii; `NL` is *New Leaf* for 3DS; `WA` is *Welcome amiibo*, the *New Leaf* expansion; `NH` is *New Horizons* for Switch; `FILM` is the *Doubutsu no Mori* Japan-exclusive film; `HHD` is *Happy Home Designer* for the Wii; and `PC` is *Pocket Camp* for mobile.
   */
  debut?: 'DNM' | 'AC' | 'E_PLUS' | 'WW' | 'CF' | 'NL' | 'WA' | 'NH' | 'FILM' | 'HHD' | 'PC';

  /**
   * Gender of the villager. In *Animal Crossing*, only male and female are used.
   */
  gender?: 'Male' | 'Female';

  /**
   * The game's internal identifier for the villager. Not all villagers have IDs; villagers who appeared in any game including or after *Wild World* have a consistent ID between games.
   */
  id?: string;

  /**
   * Image of the villager from the latest game the villager appeared in.
   */
  image_url?: string;

  /**
   * Whether the villager was an island in *Animal Crossing* for GameCube. Only a small number of villagers (36) were islanders.
   */
  islander?: boolean;

  /**
   * Name of the villager.
   */
  name?: string;

  /**
   * An object that holds villager data specific to *New Horizons*. If the villager does not appear in *New Horizons*, this field will be set to null.
   */
  nh_details?: {

/**
 * Image of the villager from *New Horizons*.
 */
'image_url'?: string;

/**
 * The villager's photo, received by the player after attaining a certain friendship level. See https://nookipedia.com/wiki/Category:New_Horizons_pictures for full list.
 */
'photo_url'?: string;

/**
 * The villager's icon of their head. See https://nookipedia.com/wiki/Category:New_Horizons_character_icons for full list.
 */
'icon_url'?: string;

/**
 * The villager's quote, as found on the back of their in-game photo.
 */
'quote'?: string;

/**
 * Each personality in *New Horizons* has two sub-personalities, currently referred to as just A and B. The effect of a sub-personality is currently unknown.
 */
'sub-personality'?: 'A' | 'B';

/**
 * The default phrase a villager will use when speaking to the player.
 */
'catchphrase'?: string;

/**
 * The default clothing that the villager wears.
 */
'clothing'?: string;

/**
 * The variation of the clothing (usually a color).
 */
'clothing_variation'?: string;

/**
 * The villager's favorite clothing styles.
 */
'fav_styles'?: Array<string>;

/**
 * The villager's favorite colors (giving the villager a gift with one of their favorite colors increases friendship points).
 */
'fav_colors'?: Array<string>;

/**
 * The villager's primary hobby, which determines most of the activities they will do around the island (e.g. education villagers will frequently read books and visit the museum). Learn more at https://nookipedia.com/wiki/Hobbies
 */
'hobby'?: 'Education' | 'Fashion' | 'Fitness' | 'Music' | 'Nature' | 'Play';

/**
 * A screenshot of the villager's house interior.
 */
'house_interior_url'?: string;

/**
 * A rendered model of the villager's house exterior. Note that this is not an official Nintendo asset, but a render based of the in-game model.
 */
'house_exterior_url'?: string;

/**
 * The wallpaper in the villager's house.
 */
'house_wallpaper'?: string;

/**
 * The flooring in the villager's house.
 */
'house_flooring'?: string;

/**
 * The music in the villager's house.
 */
'house_music'?: string;

/**
 * Any notes about the villager's music. If populated, this is usually "Does not contain a stereo initially", meaning that the villager's house will not play music unless provided with a stereo.
 */
'house_music_note'?: string;

/**
 * The name of the umbrella used by the villager.
 */
'umbrella'?: string;
};

  /**
   * The villager's personality. Note that there are no official in-game personality names; these are names that are commonly used by the community. In the case of 'sisterly', other common names include 'big sis' and 'uchi'.
   */
  personality?: 'Big sister' | 'Cranky' | 'Jock' | 'Lazy' | 'Normal' | 'Peppy' | 'Smug' | 'Snooty';

  /**
   * The villager's default phrase they use throughout conversation. This will be the phrase from the latest game (i.e. if the villager had varying phrases between *Wild World* and *New Horizons*, this will be the *New Horizons* quote).
   */
  phrase?: string;

  /**
   * Any phrases used in previous *Animal Crossing* installations. May be empty.
   */
  prev_phrases?: Array<string>;

  /**
   * The villager's quote as it appears on the back of their in-game portrait item. This will be the quote from the latest game (i.e. if the villager had varying quotes between *Wild World* and *New Horizons*, this will be the *New Horizons* quote). For villagers from older games that do not have a quote, this field will be an empty string.
   */
  quote?: string;

  /**
   * The villager's astrological star sign.
   */
  sign?: 'Aries' | 'Taurus' | 'Gemini' | 'Cancer' | 'Leo' | 'Virgo' | 'Libra' | 'Scorpio' | 'Sagittarius' | 'Capricorn' | 'Aquarius' | 'Pisces';

  /**
   * The villager's species.
   */
  species?: 'Alligator' | 'Anteater' | 'Bear' | 'Bear cub' | 'Bird' | 'Bull' | 'Cat' | 'Chicken' | 'Cow' | 'Deer' | 'Dog' | 'Duck' | 'Eagle' | 'Elephant' | 'Frog' | 'Goat' | 'Gorilla' | 'Hamster' | 'Hippo' | 'Horse' | 'Koala' | 'Kangaroo' | 'Lion' | 'Monkey' | 'Mouse' | 'Octopus' | 'Ostrich' | 'Penguin' | 'Pig' | 'Rabbit' | 'Rhinoceros' | 'Sheep' | 'Squirrel' | 'Tiger' | 'Wolf';

  /**
   * The HTML color code of the text of the villager's name badge that appears above their dialogue box when spoken to in-game. Note that to date, only *New Horizons* villagers have this field populated.
   */
  text_color?: string;

  /**
   * The HTML color code of the background of the villager's name badge that appears above their dialogue box when spoken to in-game. Note that to date, only *New Horizons* villagers have this field populated. This field may be useful for styling, such as the accent color for a Discord embed.
   */
  title_color?: string;

  /**
   * Link to the respective Nookipedia article.
   */
  url?: string;
}
